spring:
    profiles:
        active: local # this will use manually started activemq, email and mysql servers using docker-compose
#        active: local,withTestContainer # use this to start activemq, email and mysql servers with DockerContainerConfig
