version: '3'
services:
    ## we can connect to elasticsearch by connecting to http://elasticsearch:9200 on HQ (http://localhost:5000)
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.0'
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - seedappnet
    keycloak:
        image: 'quay.io/keycloak/keycloak:13.0.0'
        container_name: keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/tmp/test-realm.json
            - DB_VENDOR=h2 # don't try to discover mysql in the network
        volumes:
            - ../main-app/src/main/resources/keycloak/keycloak-export.json:/tmp/test-realm.json  #might need to delete volume to avoid dup user error
        ports:
            - 8082:8080
        networks:
            - seedappnet
    activemq_artemis:
        image: 'vromero/activemq-artemis:2.16.0'
        container_name: activemqArtemis
        environment:
            - ARTEMIS_USERNAME=admin
            - ARTEMIS_PASSWORD=admin
        ports:
            - 8161:8161  # use this to login
            - 61616:61616
        networks:
            - seedappnet
    mysql:
        image: 'mysql:8.0.25'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=seedapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        networks:
            - seedappnet
volumes:
    esdata1:
        driver: local
networks:
    seedappnet:
        driver: bridge


#run using
#docker-compose -f docker-compose.yml up
# or just docker-compose up
