spring:
    profiles:
        active: docker-local

    #Access from http://localhost:8080/h2-console/, db url: jdbc:h2:mem:testdb, username: sa
    h2:
        console:
            enabled: true

server:
    port: 8080
