spring:
    thymeleaf:
        cache: false # uncomment this if you are working on UI
        prefix: file:main-app/src/main/resources/templates/  #directly serve from src folder instead of target
    web:
        resources:
            static-locations:
                - file:src/main/resources/static/ #directly serve from src folder instead of target
                - classpath:/META-INF/resources/
                - classpath:/resources/
                - classpath:/static/
                - classpath:/public/
            cache:
                period: 0
    mvc:
        static-path-pattern: /static/**

    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:seedapp}?useUnicode=true&allowPublicKeyRetrieval=true
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:password}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none  # we use liquibase
            naming:
                physical-strategy: gt.app.hibernate.PrefixedNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    jooq:
        sql-dialect: MySQL

    elasticsearch:
        rest:
            uris: http://${ELASTICSEARCH_HOSTADDR:localhost:9200}
    artemis:
        host: ${ACTIVEMQ_ARTEMIS_HOST:localhost}
        port: ${ACTIVEMQ_ARTEMIS_PORT:61616}
        user: ${ACTIVEMQ_ARTEMIS_USERNAME:admin}
        password: ${ACTIVEMQ_ARTEMIS_PASSWORD:admin}

keycloak:
    realm: blogapp
    auth-server-url: http://localhost:${KEYCLOAK_PORT:8082}/auth/
    ssl-required: external
    resource: gateway-app-client
    public-client: true # for gateway app
    principal-attribute: name
    credentials.secret: dc168f0c-3c7f-47b9-b700-43d746978566

feign-clients:
    email-service:
        url: http://localhost:8085/ #TODO: use service discovery

logging:
    level:
        org.jooq.tools.LoggerListener: DEBUG


logging.level:
    gt: TRACE
